### ISSUE TITLE
Deal with negative and missing values in Stata files

### ISSUE THREAD

**Issue by mhebing** [ddionrails/ddi.py#1]
`read_stata()` should import correctly:
- [x] negative values
- [ ] Stata missings (`.` or `.a`)

**Comment by mhebing** [comment]
@mpahl Please review and close

**Comment by mpahl** [comment]
Status: The script reads Stata-Missings (., .a, .b etc.) as NaN.

For later: Read missings properly. Adaption for other scripts.
(see http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_stata.html)

**Comment by afuetterer** [comment]
Was this fixed?
