### ISSUE TITLE
Simple codebook tool for data previews

### ISSUE THREAD

**Issue by mhebing** [ddionrails/ddi.py#12]
Über Jinja mithilfe von http://getbootstrap.com/

**Comment by mhebing** [comment]
http://getbootstrap.com/getting-started/#template

**Comment by mhebing** [comment]
Next steps:

- [x] use [Bootstrap](http://getbootstrap.com/)
- [x] integrate [visualizations](https://github.com/ddionrails/visualization)

**Comment by mpahl** [comment]
Simple codebooks are already available in html with bootstrap
- https://github.com/ddionrails/ddi.py/blob/master/ddi/convert/template_stats.html

Also visualizations tests in function bi
- https://github.com/ddionrails/ddi.py/blob/master/ddi/convert/write_stats.py
